# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1294R8Jy__xeI3xlOTTjJ7gAXd2HqitM-
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    confusion_matrix, accuracy_score, classification_report
)
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
import seaborn as sns



#Load Data
data = pd.read_csv("processed_ev_data.csv")

X = data.drop(columns=["Price.DE."])
y = data["Price.DE."]


#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#Normalize
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)



#Neural Network Model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.fit(X_train_scaled, y_train, epochs=100, batch_size=16, validation_split=0.2, verbose=0)

y_pred_nn = model.predict(X_test_scaled).flatten()

mae_nn = mean_absolute_error(y_test, y_pred_nn)
mse_nn = mean_squared_error(y_test, y_pred_nn)
r2_nn = r2_score(y_test, y_pred_nn)

print("\n🧠 Neural Network Model Results:")
print(f"MAE: {mae_nn:.2f}")
print(f"MSE: {mse_nn:.2f}")
print(f"R²:  {r2_nn:.3f}")


#Random Forest
rf = RandomForestRegressor(n_estimators=150, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("\n🌲 Random Forest Model Results:")
print(f"MAE: {mae_rf:.2f}")
print(f"MSE: {mse_rf:.2f}")
print(f"R²:  {r2_rf:.3f}")


#Convert Prices into Categories

bins = [0, 40000, 60000, np.inf]
labels = ['Low', 'Medium', 'High']

y_test_cat = pd.cut(y_test, bins=bins, labels=labels)
y_pred_nn_cat = pd.cut(y_pred_nn, bins=bins, labels=labels)
y_pred_rf_cat = pd.cut(y_pred_rf, bins=bins, labels=labels)


#Confusion Matrix and Accuracy
def evaluate_classification(y_true, y_pred, model_name):
    print(f"\n📊 Classification Metrics for {model_name}:")
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    acc = accuracy_score(y_true, y_pred)
    print(f"Accuracy: {acc*100:.2f}%")
    print("\nConfusion Matrix:")
    print(cm)
    print("\nDetailed Report:")
    print(classification_report(y_true, y_pred))


# Neural Network
evaluate_classification(y_test_cat, y_pred_nn_cat, "Neural Network")

# Random Forest
evaluate_classification(y_test_cat, y_pred_rf_cat, "Random Forest")


#Example Prediction
example = X_test.iloc[:1]
example_scaled = scaler.transform(example)
predicted_price_nn = model.predict(example_scaled)[0][0]
predicted_price_rf = rf.predict(example)[0]

print("\nExample Prediction:")
print(f"Actual Price: {y_test.iloc[0]:.2f}")
print(f"Neural Network Predicted Price: {predicted_price_nn:.2f}")
print(f"Random Forest Predicted Price: {predicted_price_rf:.2f}")